export default {
    NEXT_PAGE : 'NEXT_PAGE',
    PREVIOUS_PAGE : 'PREVIOUS_PAGE',
    FETCH_USERS_REQUEST : 'FETCH_USERS_REQUEST',
    FETCH_USERS_SUCCESS : 'FETCH_USERS_SUCCESS',
    FETCH_USERS_FAILURE : 'FETCH_USERS_FAILURE'
}