const loginActionTypes = {
    LOGIN_USER : 'LOGIN_USER',
    LOGIN_USER_REQUEST : 'LOGIN_USER_REQUEST',
    LOGIN_USER_SUCCESS : 'LOGIN_USER_SUCCESS',
    LOGIN_USER_FAILURE : 'LOGIN_USER_FAILURE'
}

export default loginActionTypes;