const registerActionTypes = {
    REGISTER_USER_REQUEST : 'REGISTER_USER_REQUEST',
    REGISTER_USER : 'REGISTER_USER',
    REGISTER_USER_SUCCESS : 'REGISTER_USER_SUCCESS',
    REGISTER_USER_FAILURE : 'REGISTER_USER_FAILURE'
}

export default registerActionTypes;